import Foundation
import Testing
@testable import ssssh

/// Every expected byte string below was generated by real `protoc --encode`
/// against ET's actual `proto/ET.proto`/`proto/ETerminal.proto` (protoc
/// 35.1) -- not hand-derived. E.g.:
/// `echo 'clientId: "hi" version: 3' | protoc --encode=et.ConnectRequest ET.proto | xxd`
struct ETMessagesTests {
    @Test("ConnectRequest encodes to match real protoc output")
    func connectRequestEncode() {
        var request = ETConnectRequest()
        request.clientId = "hi"
        request.version = 3
        #expect(request.encode() == [0x0a, 0x02, 0x68, 0x69, 0x10, 0x03])
    }

    @Test("ConnectResponse encodes to match real protoc output")
    func connectResponseEncode() {
        var response = ETConnectResponse()
        response.status = .returningClient
        response.error = "oops"
        #expect(response.encode() == [0x08, 0x02, 0x12, 0x04, 0x6f, 0x6f, 0x70, 0x73])
    }

    @Test("TerminalInfo encodes to match real protoc output")
    func terminalInfoEncode() {
        var info = ETTerminalInfo()
        info.id = "abc"
        info.row = 24
        info.column = 80
        info.width = 640
        info.height = 480
        #expect(info.encode() == [
            0x0a, 0x03, 0x61, 0x62, 0x63, 0x10, 0x18, 0x18, 0x50, 0x20, 0x80, 0x05, 0x28, 0xe0, 0x03,
        ])
    }

    @Test("TermInit encodes two parallel repeated string fields to match real protoc output")
    func termInitEncode() {
        var init_ = ETTermInit()
        init_.environmentNames = ["A", "B"]
        init_.environmentValues = ["1", "2"]
        #expect(init_.encode() == [
            0x0a, 0x01, 0x41, 0x0a, 0x01, 0x42, 0x12, 0x01, 0x31, 0x12, 0x01, 0x32,
        ])
    }

    @Test("TerminalUserInfo encodes a negative int64 field as the full sign-extended varint, matching real protoc output")
    func terminalUserInfoEncodeNegative() {
        var info = ETTerminalUserInfo()
        info.id = "myid"
        info.passkey = "mypasskey"
        info.uid = -1
        info.gid = 5000
        info.fd = 3
        #expect(info.encode() == [
            0x0a, 0x04, 0x6d, 0x79, 0x69, 0x64, 0x12, 0x09, 0x6d, 0x79, 0x70, 0x61, 0x73, 0x73, 0x6b,
            0x65, 0x79, 0x18, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x20, 0x88,
            0x27, 0x28, 0x03,
        ])
    }

    @Test("TerminalBuffer encodes to match real protoc output")
    func terminalBufferEncode() {
        var buffer = ETTerminalBuffer()
        buffer.buffer = Array("hello\n".utf8)
        #expect(buffer.encode() == [0x0a, 0x06, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x0a])
    }

    @Test("decode() parses real protoc-encoded bytes, including a sign-extended negative int64")
    func decodesRealProtocBytes() throws {
        let decoded = try ETTerminalUserInfo.decode([
            0x0a, 0x04, 0x6d, 0x79, 0x69, 0x64, 0x12, 0x09, 0x6d, 0x79, 0x70, 0x61, 0x73, 0x73, 0x6b,
            0x65, 0x79, 0x18, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01, 0x20, 0x88,
            0x27, 0x28, 0x03,
        ])
        #expect(decoded.id == "myid")
        #expect(decoded.passkey == "mypasskey")
        #expect(decoded.uid == -1)
        #expect(decoded.gid == 5000)
        #expect(decoded.fd == 3)
    }

    @Test("decode() parses real protoc-encoded repeated string fields")
    func decodesRealProtocRepeatedFields() throws {
        let decoded = try ETTermInit.decode([
            0x0a, 0x01, 0x41, 0x0a, 0x01, 0x42, 0x12, 0x01, 0x31, 0x12, 0x01, 0x32,
        ])
        #expect(decoded.environmentNames == ["A", "B"])
        #expect(decoded.environmentValues == ["1", "2"])
    }

    @Test("encode()/decode() round-trips TerminalBuffer")
    func roundTripsTerminalBuffer() throws {
        var buffer = ETTerminalBuffer()
        buffer.buffer = Array((0..<64).map { UInt8($0) })
        let decoded = try ETTerminalBuffer.decode(buffer.encode())
        #expect(decoded.buffer == buffer.buffer)
    }

    @Test("ETPacketHeader's TerminalPacketType and EtPacketType ranges don't collide")
    func packetHeaderRangesDoNotCollide() {
        let terminalRange: Set<UInt8> = [0, 1, 2, 5, 6, 7, 8, 9, 10]
        let etRange: Set<UInt8> = [252, 253, 254]
        #expect(terminalRange.isDisjoint(with: etRange))
    }

    @Test("SequenceHeader encodes to match real protoc output")
    func sequenceHeaderEncode() throws {
        var header = ETSequenceHeader()
        header.sequenceNumber = 42
        #expect(header.encode() == [0x08, 0x2a])
        #expect(try ETSequenceHeader.decode([0x08, 0x2a]).sequenceNumber == 42)
    }

    @Test("CatchupBuffer encodes repeated bytes fields to match real protoc output")
    func catchupBufferEncode() throws {
        var catchup = ETCatchupBuffer()
        catchup.buffer = [Array("hello".utf8), Array("world!".utf8)]
        let expected: [UInt8] = [
            0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x0a, 0x06, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x21,
        ]
        #expect(catchup.encode() == expected)
        let decoded = try ETCatchupBuffer.decode(expected)
        #expect(decoded.buffer == [Array("hello".utf8), Array("world!".utf8)])
    }

    @Test("parseFields rejects a length-delimited field whose length exceeds the remaining bytes, instead of trapping")
    func parseFieldsRejectsOversizedLength() {
        // Tag for field 1, wire type 2 (length-delimited) = (1 << 3) | 2 = 0x0a,
        // followed by a varint-encoded length far larger than any real
        // message and no matching payload -- the same family of hardening
        // this app already applies to MoshProtobuf.parseFields (an
        // authenticated peer can still send malformed data; `Int(length)`
        // must never be reached before this bound is checked, since a
        // length near `UInt64.max` traps that conversion outright).
        let maliciousBytes: [UInt8] = [0x0a, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x01]
        #expect(throws: ETProtobuf.DecodeError.self) {
            _ = try ETProtobuf.parseFields(maliciousBytes)
        }
    }
}
